
name: test:quiet

on:
  push:
    paths:
    - 'action.yml'
    - '.github/workflows/quiet.yml'
  workflow_dispatch:

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: idleberg/setup-playdate-sdk@main
      with:
        quiet: true

    - name: Test environment variable
      run: |
        if [ -z "${PLAYDATE_SDK_PATH}" ]; then
          echo "PLAYDATE_SDK_PATH is not defined or empty"
          exit 1
        fi

        $PLAYDATE_SDK_PATH/bin/pdc --version

    - name: Print version
      run: pdc --version

    - name: Compile game
      run: pdc --verbose ${GITHUB_WORKSPACE}/.github/source
